### ISSUE TITLE
友军正在努力抄写中

### ISSUE THREAD

**Issue by CMGS** [laincloud/white-paper#53]
RT……
我们自己的项目也打算参照 lain 开源，因此在努力抄贵书中……
不知道有什么需要注意的么- -

**Comment by sunyi00** [comment]
法务，LICENSE，还有啥？ @ericpai

**Comment by ericpai** [comment]
@CMGS @sunyi00 如果是白皮书的话，acknowledgement最好也来一个章节。

**Comment by CMGS** [comment]
OK 没问题

**Comment by CMGS** [comment]
https://projecteru2.gitbooks.io/white-paper/content/brief.html 已加了一章节介绍历史渊源哈哈哈
